// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sts.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	sts.proto

It has these top-level messages:
	GameTableInfoArgs
	CardsInfo
	Player
	StsRes
	PlayerAction
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type GameTableInfoArgs struct {
	RoomId  int32        `protobuf:"varint,1,opt,name=room_id,json=roomId" json:"room_id,omitempty"`
	TableId string       `protobuf:"bytes,2,opt,name=table_id,json=tableId" json:"table_id,omitempty"`
	Max     int32        `protobuf:"varint,3,opt,name=max" json:"max,omitempty"`
	Start   int32        `protobuf:"varint,4,opt,name=start" json:"start,omitempty"`
	End     int32        `protobuf:"varint,5,opt,name=end" json:"end,omitempty"`
	Cards   []*CardsInfo `protobuf:"bytes,6,rep,name=cards" json:"cards,omitempty"`
	Button  int32        `protobuf:"varint,7,opt,name=button" json:"button,omitempty"`
	Sb      int32        `protobuf:"varint,8,opt,name=sb" json:"sb,omitempty"`
	Bb      int32        `protobuf:"varint,9,opt,name=bb" json:"bb,omitempty"`
	SbPos   int32        `protobuf:"varint,10,opt,name=sb_pos,json=sbPos" json:"sb_pos,omitempty"`
	BbPos   int32        `protobuf:"varint,11,opt,name=bb_pos,json=bbPos" json:"bb_pos,omitempty"`
	Pot     []int32      `protobuf:"varint,12,rep,packed,name=pot" json:"pot,omitempty"`
	Players []*Player    `protobuf:"bytes,13,rep,name=players" json:"players,omitempty"`
}

func (m *GameTableInfoArgs) Reset()                    { *m = GameTableInfoArgs{} }
func (m *GameTableInfoArgs) String() string            { return proto1.CompactTextString(m) }
func (*GameTableInfoArgs) ProtoMessage()               {}
func (*GameTableInfoArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GameTableInfoArgs) GetRoomId() int32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *GameTableInfoArgs) GetTableId() string {
	if m != nil {
		return m.TableId
	}
	return ""
}

func (m *GameTableInfoArgs) GetMax() int32 {
	if m != nil {
		return m.Max
	}
	return 0
}

func (m *GameTableInfoArgs) GetStart() int32 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *GameTableInfoArgs) GetEnd() int32 {
	if m != nil {
		return m.End
	}
	return 0
}

func (m *GameTableInfoArgs) GetCards() []*CardsInfo {
	if m != nil {
		return m.Cards
	}
	return nil
}

func (m *GameTableInfoArgs) GetButton() int32 {
	if m != nil {
		return m.Button
	}
	return 0
}

func (m *GameTableInfoArgs) GetSb() int32 {
	if m != nil {
		return m.Sb
	}
	return 0
}

func (m *GameTableInfoArgs) GetBb() int32 {
	if m != nil {
		return m.Bb
	}
	return 0
}

func (m *GameTableInfoArgs) GetSbPos() int32 {
	if m != nil {
		return m.SbPos
	}
	return 0
}

func (m *GameTableInfoArgs) GetBbPos() int32 {
	if m != nil {
		return m.BbPos
	}
	return 0
}

func (m *GameTableInfoArgs) GetPot() []int32 {
	if m != nil {
		return m.Pot
	}
	return nil
}

func (m *GameTableInfoArgs) GetPlayers() []*Player {
	if m != nil {
		return m.Players
	}
	return nil
}

type CardsInfo struct {
	Suit  int32 `protobuf:"varint,1,opt,name=suit" json:"suit,omitempty"`
	Value int32 `protobuf:"varint,2,opt,name=value" json:"value,omitempty"`
}

func (m *CardsInfo) Reset()                    { *m = CardsInfo{} }
func (m *CardsInfo) String() string            { return proto1.CompactTextString(m) }
func (*CardsInfo) ProtoMessage()               {}
func (*CardsInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CardsInfo) GetSuit() int32 {
	if m != nil {
		return m.Suit
	}
	return 0
}

func (m *CardsInfo) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type Player struct {
	Id             int32           `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Nickname       string          `protobuf:"bytes,2,opt,name=nickname" json:"nickname,omitempty"`
	Avatar         string          `protobuf:"bytes,3,opt,name=avatar" json:"avatar,omitempty"`
	Pos            int32           `protobuf:"varint,4,opt,name=pos" json:"pos,omitempty"`
	Bet            int32           `protobuf:"varint,5,opt,name=bet" json:"bet,omitempty"`
	Win            int32           `protobuf:"varint,6,opt,name=win" json:"win,omitempty"`
	FormerChips    int32           `protobuf:"varint,7,opt,name=former_chips,json=formerChips" json:"former_chips,omitempty"`
	CurrentChips   int32           `protobuf:"varint,8,opt,name=current_chips,json=currentChips" json:"current_chips,omitempty"`
	Action         string          `protobuf:"bytes,9,opt,name=action" json:"action,omitempty"`
	Cards          []*CardsInfo    `protobuf:"bytes,10,rep,name=cards" json:"cards,omitempty"`
	HandLevel      int32           `protobuf:"varint,11,opt,name=hand_level,json=handLevel" json:"hand_level,omitempty"`
	HandFinalValue int32           `protobuf:"varint,12,opt,name=hand_final_value,json=handFinalValue" json:"hand_final_value,omitempty"`
	Actions        []*PlayerAction `protobuf:"bytes,13,rep,name=actions" json:"actions,omitempty"`
}

func (m *Player) Reset()                    { *m = Player{} }
func (m *Player) String() string            { return proto1.CompactTextString(m) }
func (*Player) ProtoMessage()               {}
func (*Player) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Player) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Player) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *Player) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *Player) GetPos() int32 {
	if m != nil {
		return m.Pos
	}
	return 0
}

func (m *Player) GetBet() int32 {
	if m != nil {
		return m.Bet
	}
	return 0
}

func (m *Player) GetWin() int32 {
	if m != nil {
		return m.Win
	}
	return 0
}

func (m *Player) GetFormerChips() int32 {
	if m != nil {
		return m.FormerChips
	}
	return 0
}

func (m *Player) GetCurrentChips() int32 {
	if m != nil {
		return m.CurrentChips
	}
	return 0
}

func (m *Player) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *Player) GetCards() []*CardsInfo {
	if m != nil {
		return m.Cards
	}
	return nil
}

func (m *Player) GetHandLevel() int32 {
	if m != nil {
		return m.HandLevel
	}
	return 0
}

func (m *Player) GetHandFinalValue() int32 {
	if m != nil {
		return m.HandFinalValue
	}
	return 0
}

func (m *Player) GetActions() []*PlayerAction {
	if m != nil {
		return m.Actions
	}
	return nil
}

type StsRes struct {
	Ret int32  `protobuf:"varint,1,opt,name=ret" json:"ret,omitempty"`
	Msg string `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
}

func (m *StsRes) Reset()                    { *m = StsRes{} }
func (m *StsRes) String() string            { return proto1.CompactTextString(m) }
func (*StsRes) ProtoMessage()               {}
func (*StsRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *StsRes) GetRet() int32 {
	if m != nil {
		return m.Ret
	}
	return 0
}

func (m *StsRes) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type PlayerAction struct {
	Action string `protobuf:"bytes,1,opt,name=action" json:"action,omitempty"`
	Bet    int32  `protobuf:"varint,2,opt,name=bet" json:"bet,omitempty"`
}

func (m *PlayerAction) Reset()                    { *m = PlayerAction{} }
func (m *PlayerAction) String() string            { return proto1.CompactTextString(m) }
func (*PlayerAction) ProtoMessage()               {}
func (*PlayerAction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *PlayerAction) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *PlayerAction) GetBet() int32 {
	if m != nil {
		return m.Bet
	}
	return 0
}

func init() {
	proto1.RegisterType((*GameTableInfoArgs)(nil), "proto.GameTableInfoArgs")
	proto1.RegisterType((*CardsInfo)(nil), "proto.CardsInfo")
	proto1.RegisterType((*Player)(nil), "proto.Player")
	proto1.RegisterType((*StsRes)(nil), "proto.StsRes")
	proto1.RegisterType((*PlayerAction)(nil), "proto.PlayerAction")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for StsService service

type StsServiceClient interface {
	// 获取游戏信息
	GameInfo(ctx context.Context, in *GameTableInfoArgs, opts ...grpc.CallOption) (*StsRes, error)
}

type stsServiceClient struct {
	cc *grpc.ClientConn
}

func NewStsServiceClient(cc *grpc.ClientConn) StsServiceClient {
	return &stsServiceClient{cc}
}

func (c *stsServiceClient) GameInfo(ctx context.Context, in *GameTableInfoArgs, opts ...grpc.CallOption) (*StsRes, error) {
	out := new(StsRes)
	err := grpc.Invoke(ctx, "/proto.StsService/GameInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for StsService service

type StsServiceServer interface {
	// 获取游戏信息
	GameInfo(context.Context, *GameTableInfoArgs) (*StsRes, error)
}

func RegisterStsServiceServer(s *grpc.Server, srv StsServiceServer) {
	s.RegisterService(&_StsService_serviceDesc, srv)
}

func _StsService_GameInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GameTableInfoArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StsServiceServer).GameInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.StsService/GameInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StsServiceServer).GameInfo(ctx, req.(*GameTableInfoArgs))
	}
	return interceptor(ctx, in, info, handler)
}

var _StsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.StsService",
	HandlerType: (*StsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GameInfo",
			Handler:    _StsService_GameInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sts.proto",
}

func init() { proto1.RegisterFile("sts.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 528 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x93, 0x5f, 0x6b, 0xdb, 0x3c,
	0x14, 0xc6, 0xdf, 0xd8, 0xb5, 0x13, 0x9f, 0x24, 0x25, 0xaf, 0xf6, 0x4f, 0x2b, 0x0c, 0x32, 0x0f,
	0xb6, 0x5c, 0x6c, 0xbd, 0xe8, 0x28, 0xec, 0xb6, 0x04, 0x36, 0x02, 0xbb, 0x28, 0xce, 0xd8, 0x6d,
	0x90, 0x6c, 0xa5, 0x15, 0x73, 0x24, 0x23, 0x29, 0xe9, 0x76, 0xbb, 0x8f, 0xb7, 0x4f, 0x35, 0x8e,
	0x24, 0x67, 0x2d, 0x83, 0x5d, 0xe5, 0x3c, 0xbf, 0x73, 0x70, 0x1e, 0x3d, 0x47, 0x82, 0xc2, 0x3a,
	0x7b, 0xde, 0x19, 0xed, 0x34, 0xc9, 0xfc, 0x4f, 0xf9, 0x2b, 0x81, 0xff, 0x3f, 0xb1, 0x9d, 0xf8,
	0xc2, 0x78, 0x2b, 0x56, 0x6a, 0xab, 0xaf, 0xcc, 0x8d, 0x25, 0xcf, 0x60, 0x68, 0xb4, 0xde, 0x6d,
	0x64, 0x43, 0x07, 0xf3, 0xc1, 0x22, 0xab, 0x72, 0x94, 0xab, 0x86, 0x3c, 0x87, 0x91, 0xc3, 0x49,
	0xec, 0x24, 0xf3, 0xc1, 0xa2, 0xa8, 0x86, 0x5e, 0xaf, 0x1a, 0x32, 0x83, 0x74, 0xc7, 0xbe, 0xd3,
	0xd4, 0xcf, 0x63, 0x49, 0x1e, 0x43, 0x66, 0x1d, 0x33, 0x8e, 0x9e, 0x78, 0x16, 0x04, 0xce, 0x09,
	0xd5, 0xd0, 0x2c, 0xcc, 0x09, 0xd5, 0x90, 0xd7, 0x90, 0xd5, 0xcc, 0x34, 0x96, 0xe6, 0xf3, 0x74,
	0x31, 0xbe, 0x98, 0x05, 0x87, 0xe7, 0x4b, 0x64, 0x68, 0xa9, 0x0a, 0x6d, 0xf2, 0x14, 0x72, 0xbe,
	0x77, 0x4e, 0x2b, 0x3a, 0x0c, 0xa6, 0x82, 0x22, 0xa7, 0x90, 0x58, 0x4e, 0x47, 0x9e, 0x25, 0x96,
	0xa3, 0xe6, 0x9c, 0x16, 0x41, 0x73, 0x4e, 0x9e, 0x40, 0x6e, 0xf9, 0xa6, 0xd3, 0x96, 0x42, 0x34,
	0xc2, 0xaf, 0xb5, 0x45, 0xcc, 0x03, 0x1e, 0x07, 0xcc, 0x3d, 0x9e, 0x41, 0xda, 0x69, 0x47, 0x27,
	0xf3, 0x14, 0xfd, 0x75, 0xda, 0x91, 0x37, 0x30, 0xec, 0x5a, 0xf6, 0x43, 0x18, 0x4b, 0xa7, 0xde,
	0xe1, 0x34, 0x3a, 0xbc, 0xf6, 0xb4, 0xea, 0xbb, 0xe5, 0x25, 0x14, 0x47, 0xd3, 0x84, 0xc0, 0x89,
	0xdd, 0x4b, 0x17, 0x03, 0xf4, 0x35, 0x26, 0x72, 0x60, 0xed, 0x5e, 0xf8, 0xec, 0xb2, 0x2a, 0x88,
	0xf2, 0x67, 0x0a, 0x79, 0xf8, 0x14, 0x5a, 0x3f, 0x66, 0x9e, 0xc8, 0x86, 0x9c, 0xc1, 0x48, 0xc9,
	0xfa, 0x9b, 0x62, 0x3b, 0x11, 0xf3, 0x3e, 0x6a, 0x8c, 0x83, 0x1d, 0x98, 0x63, 0xc6, 0x67, 0x5e,
	0x54, 0x51, 0x85, 0x03, 0xd8, 0x18, 0x3a, 0x96, 0x48, 0xb8, 0x70, 0x7d, 0xe4, 0x5c, 0xf8, 0x25,
	0xdc, 0x49, 0x45, 0xf3, 0x40, 0xee, 0xa4, 0x22, 0x2f, 0x61, 0xb2, 0xd5, 0x66, 0x27, 0xcc, 0xa6,
	0xbe, 0x95, 0x9d, 0x8d, 0x11, 0x8f, 0x03, 0x5b, 0x22, 0x22, 0xaf, 0x60, 0x5a, 0xef, 0x8d, 0x11,
	0xca, 0xc5, 0x99, 0x10, 0xf9, 0x24, 0xc2, 0x30, 0x84, 0xae, 0x6a, 0x27, 0xb5, 0xf2, 0x0b, 0x40,
	0x57, 0x5e, 0xfd, 0x59, 0x32, 0xfc, 0x7b, 0xc9, 0x2f, 0x00, 0x6e, 0x99, 0x6a, 0x36, 0xad, 0x38,
	0x88, 0x36, 0x6e, 0xa6, 0x40, 0xf2, 0x19, 0x01, 0x59, 0xc0, 0xcc, 0xb7, 0xb7, 0x52, 0xb1, 0x76,
	0x13, 0xc2, 0x9c, 0xf8, 0xa1, 0x53, 0xe4, 0x1f, 0x11, 0x7f, 0x45, 0x4a, 0xde, 0xc1, 0x30, 0xfc,
	0x75, 0xbf, 0xb5, 0x47, 0x0f, 0xb6, 0x76, 0xe5, 0x7b, 0x55, 0x3f, 0x53, 0xbe, 0x85, 0x7c, 0xed,
	0x6c, 0x25, 0x7c, 0x5a, 0x46, 0xf4, 0x7b, 0xc3, 0xd2, 0x5f, 0x6d, 0x7b, 0x13, 0x17, 0x80, 0x65,
	0xf9, 0x01, 0x26, 0xf7, 0x3f, 0x73, 0xef, 0xd4, 0x83, 0x07, 0xa7, 0x8e, 0xc9, 0x27, 0xc7, 0xe4,
	0x2f, 0x96, 0x00, 0x6b, 0x67, 0xd7, 0xc2, 0x1c, 0x64, 0x2d, 0xc8, 0x25, 0x8c, 0xf0, 0xf5, 0xf9,
	0x0b, 0x43, 0xa3, 0xbf, 0xbf, 0x9e, 0xe3, 0x59, 0x7f, 0xdf, 0x82, 0xc1, 0xf2, 0x3f, 0x9e, 0x7b,
	0xfd, 0xfe, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x96, 0x13, 0xbf, 0x3a, 0xd0, 0x03, 0x00, 0x00,
}
