// Code generated by protoc-gen-go. DO NOT EDIT.
// source: task.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	task.proto

It has these top-level messages:
	GameInfoArgs
	PlayerInfo
	BaseRes
	PlayerActionArgs
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type GameInfoArgs struct {
	RoomType  int32         `protobuf:"varint,1,opt,name=room_type,json=roomType" json:"room_type,omitempty"`
	MatchType int32         `protobuf:"varint,2,opt,name=match_type,json=matchType" json:"match_type,omitempty"`
	Winner    int32         `protobuf:"varint,3,opt,name=winner" json:"winner,omitempty"`
	Players   []*PlayerInfo `protobuf:"bytes,4,rep,name=players" json:"players,omitempty"`
	Time      int32         `protobuf:"varint,5,opt,name=time" json:"time,omitempty"`
}

func (m *GameInfoArgs) Reset()                    { *m = GameInfoArgs{} }
func (m *GameInfoArgs) String() string            { return proto1.CompactTextString(m) }
func (*GameInfoArgs) ProtoMessage()               {}
func (*GameInfoArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GameInfoArgs) GetRoomType() int32 {
	if m != nil {
		return m.RoomType
	}
	return 0
}

func (m *GameInfoArgs) GetMatchType() int32 {
	if m != nil {
		return m.MatchType
	}
	return 0
}

func (m *GameInfoArgs) GetWinner() int32 {
	if m != nil {
		return m.Winner
	}
	return 0
}

func (m *GameInfoArgs) GetPlayers() []*PlayerInfo {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *GameInfoArgs) GetTime() int32 {
	if m != nil {
		return m.Time
	}
	return 0
}

// 玩家信息
type PlayerInfo struct {
	Id        int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	HandLevel int32 `protobuf:"varint,2,opt,name=hand_level,json=handLevel" json:"hand_level,omitempty"`
	IsAllin   int32 `protobuf:"varint,3,opt,name=is_allin,json=isAllin" json:"is_allin,omitempty"`
	AllBet    int32 `protobuf:"varint,4,opt,name=all_bet,json=allBet" json:"all_bet,omitempty"`
}

func (m *PlayerInfo) Reset()                    { *m = PlayerInfo{} }
func (m *PlayerInfo) String() string            { return proto1.CompactTextString(m) }
func (*PlayerInfo) ProtoMessage()               {}
func (*PlayerInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PlayerInfo) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PlayerInfo) GetHandLevel() int32 {
	if m != nil {
		return m.HandLevel
	}
	return 0
}

func (m *PlayerInfo) GetIsAllin() int32 {
	if m != nil {
		return m.IsAllin
	}
	return 0
}

func (m *PlayerInfo) GetAllBet() int32 {
	if m != nil {
		return m.AllBet
	}
	return 0
}

type BaseRes struct {
	Ret int32  `protobuf:"varint,1,opt,name=ret" json:"ret,omitempty"`
	Msg string `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
}

func (m *BaseRes) Reset()                    { *m = BaseRes{} }
func (m *BaseRes) String() string            { return proto1.CompactTextString(m) }
func (*BaseRes) ProtoMessage()               {}
func (*BaseRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *BaseRes) GetRet() int32 {
	if m != nil {
		return m.Ret
	}
	return 0
}

func (m *BaseRes) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type PlayerActionArgs struct {
	RoomType  int32 `protobuf:"varint,1,opt,name=room_type,json=roomType" json:"room_type,omitempty"`
	MatchType int32 `protobuf:"varint,2,opt,name=match_type,json=matchType" json:"match_type,omitempty"`
	Id        int32 `protobuf:"varint,3,opt,name=id" json:"id,omitempty"`
	Type      int32 `protobuf:"varint,4,opt,name=type" json:"type,omitempty"`
	Time      int32 `protobuf:"varint,5,opt,name=time" json:"time,omitempty"`
}

func (m *PlayerActionArgs) Reset()                    { *m = PlayerActionArgs{} }
func (m *PlayerActionArgs) String() string            { return proto1.CompactTextString(m) }
func (*PlayerActionArgs) ProtoMessage()               {}
func (*PlayerActionArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PlayerActionArgs) GetRoomType() int32 {
	if m != nil {
		return m.RoomType
	}
	return 0
}

func (m *PlayerActionArgs) GetMatchType() int32 {
	if m != nil {
		return m.MatchType
	}
	return 0
}

func (m *PlayerActionArgs) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PlayerActionArgs) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *PlayerActionArgs) GetTime() int32 {
	if m != nil {
		return m.Time
	}
	return 0
}

func init() {
	proto1.RegisterType((*GameInfoArgs)(nil), "proto.GameInfoArgs")
	proto1.RegisterType((*PlayerInfo)(nil), "proto.PlayerInfo")
	proto1.RegisterType((*BaseRes)(nil), "proto.BaseRes")
	proto1.RegisterType((*PlayerActionArgs)(nil), "proto.PlayerActionArgs")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for TaskService service

type TaskServiceClient interface {
	// 获取所有房间信息
	GameOver(ctx context.Context, in *GameInfoArgs, opts ...grpc.CallOption) (*BaseRes, error)
	// 更新房间信息
	PlayerEvent(ctx context.Context, in *PlayerActionArgs, opts ...grpc.CallOption) (*BaseRes, error)
}

type taskServiceClient struct {
	cc *grpc.ClientConn
}

func NewTaskServiceClient(cc *grpc.ClientConn) TaskServiceClient {
	return &taskServiceClient{cc}
}

func (c *taskServiceClient) GameOver(ctx context.Context, in *GameInfoArgs, opts ...grpc.CallOption) (*BaseRes, error) {
	out := new(BaseRes)
	err := grpc.Invoke(ctx, "/proto.TaskService/GameOver", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) PlayerEvent(ctx context.Context, in *PlayerActionArgs, opts ...grpc.CallOption) (*BaseRes, error) {
	out := new(BaseRes)
	err := grpc.Invoke(ctx, "/proto.TaskService/PlayerEvent", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TaskService service

type TaskServiceServer interface {
	// 获取所有房间信息
	GameOver(context.Context, *GameInfoArgs) (*BaseRes, error)
	// 更新房间信息
	PlayerEvent(context.Context, *PlayerActionArgs) (*BaseRes, error)
}

func RegisterTaskServiceServer(s *grpc.Server, srv TaskServiceServer) {
	s.RegisterService(&_TaskService_serviceDesc, srv)
}

func _TaskService_GameOver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GameInfoArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).GameOver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TaskService/GameOver",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).GameOver(ctx, req.(*GameInfoArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_PlayerEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayerActionArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).PlayerEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TaskService/PlayerEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).PlayerEvent(ctx, req.(*PlayerActionArgs))
	}
	return interceptor(ctx, in, info, handler)
}

var _TaskService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.TaskService",
	HandlerType: (*TaskServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GameOver",
			Handler:    _TaskService_GameOver_Handler,
		},
		{
			MethodName: "PlayerEvent",
			Handler:    _TaskService_PlayerEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "task.proto",
}

func init() { proto1.RegisterFile("task.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 349 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x51, 0x5d, 0x4b, 0xeb, 0x40,
	0x10, 0xbd, 0x69, 0xd2, 0xa6, 0x9d, 0x5e, 0x4a, 0xef, 0x5c, 0xb8, 0xcd, 0x55, 0x84, 0x92, 0xa7,
	0x82, 0x58, 0xb0, 0xbe, 0xf8, 0xda, 0x82, 0x88, 0x20, 0x28, 0xb1, 0xef, 0x61, 0xdb, 0x8e, 0xed,
	0xd2, 0xcd, 0x07, 0xbb, 0x4b, 0xa4, 0xfe, 0x00, 0xff, 0x88, 0x7f, 0x54, 0x76, 0xb3, 0xb5, 0x8a,
	0xbe, 0xf9, 0x94, 0x99, 0x33, 0x27, 0x3b, 0xe7, 0x9c, 0x01, 0xd0, 0x4c, 0x6d, 0xc7, 0xa5, 0x2c,
	0x74, 0x81, 0x4d, 0xfb, 0x89, 0x5f, 0x3d, 0xf8, 0x7d, 0xcd, 0x32, 0xba, 0xc9, 0x1f, 0x8b, 0xa9,
	0x5c, 0x2b, 0x3c, 0x86, 0x8e, 0x2c, 0x8a, 0x2c, 0xd5, 0xbb, 0x92, 0x22, 0x6f, 0xe8, 0x8d, 0x9a,
	0x49, 0xdb, 0x00, 0xf3, 0x5d, 0x49, 0x78, 0x02, 0x90, 0x31, 0xbd, 0xdc, 0xd4, 0xd3, 0x86, 0x9d,
	0x76, 0x2c, 0x62, 0xc7, 0xff, 0xa0, 0xf5, 0xc4, 0xf3, 0x9c, 0x64, 0xe4, 0xdb, 0x91, 0xeb, 0xf0,
	0x14, 0xc2, 0x52, 0xb0, 0x1d, 0x49, 0x15, 0x05, 0x43, 0x7f, 0xd4, 0x9d, 0xfc, 0xa9, 0x45, 0x8c,
	0xef, 0x2d, 0x6a, 0x76, 0x27, 0x7b, 0x06, 0x22, 0x04, 0x9a, 0x67, 0x14, 0x35, 0xed, 0x13, 0xb6,
	0x8e, 0x0b, 0x80, 0x03, 0x15, 0x7b, 0xd0, 0xe0, 0x2b, 0xa7, 0xad, 0xc1, 0x57, 0x46, 0xd5, 0x86,
	0xe5, 0xab, 0x54, 0x50, 0x45, 0x62, 0xaf, 0xca, 0x20, 0xb7, 0x06, 0xc0, 0xff, 0xd0, 0xe6, 0x2a,
	0x65, 0x42, 0xf0, 0xdc, 0xe9, 0x0a, 0xb9, 0x9a, 0x9a, 0x16, 0x07, 0x10, 0x32, 0x21, 0xd2, 0x05,
	0xe9, 0x28, 0xa8, 0x15, 0x33, 0x21, 0x66, 0xa4, 0xe3, 0x33, 0x08, 0x67, 0x4c, 0x51, 0x42, 0x0a,
	0xfb, 0xe0, 0x4b, 0xd2, 0x6e, 0x9d, 0x29, 0x0d, 0x92, 0xa9, 0xb5, 0x5d, 0xd4, 0x49, 0x4c, 0x19,
	0xbf, 0x78, 0xd0, 0xaf, 0x05, 0x4e, 0x97, 0x9a, 0x17, 0xf9, 0x8f, 0x93, 0xac, 0x2d, 0xfa, 0xef,
	0x16, 0x4d, 0x28, 0x86, 0x18, 0xb8, 0x50, 0x0c, 0xe7, 0x9b, 0xa0, 0x26, 0xcf, 0xd0, 0x9d, 0x33,
	0xb5, 0x7d, 0x20, 0x59, 0xf1, 0x25, 0xe1, 0x39, 0xb4, 0xcd, 0x71, 0xef, 0x2a, 0x92, 0xf8, 0xd7,
	0x65, 0xfe, 0xf1, 0xda, 0x47, 0x3d, 0x07, 0x3a, 0xb3, 0xf1, 0x2f, 0xbc, 0x84, 0x6e, 0xed, 0xe4,
	0xaa, 0xa2, 0x5c, 0xe3, 0xe0, 0xd3, 0xa5, 0x0e, 0xee, 0xbe, 0xfe, 0xb9, 0x68, 0x59, 0xe0, 0xe2,
	0x2d, 0x00, 0x00, 0xff, 0xff, 0xfe, 0xb5, 0x93, 0x2d, 0x66, 0x02, 0x00, 0x00,
}
