// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type TokenInfoArgs struct {
	UserId     int32  `protobuf:"varint,1,opt,name=UserId" json:"UserId,omitempty"`
	AppFrom    string `protobuf:"bytes,2,opt,name=AppFrom" json:"AppFrom,omitempty"`
	AppChannel string `protobuf:"bytes,3,opt,name=AppChannel" json:"AppChannel,omitempty"`
	AppVer     int32  `protobuf:"varint,4,opt,name=AppVer" json:"AppVer,omitempty"`
	UniqueId   string `protobuf:"bytes,5,opt,name=UniqueId" json:"UniqueId,omitempty"`
	Token      string `protobuf:"bytes,6,opt,name=Token" json:"Token,omitempty"`
}

func (m *TokenInfoArgs) Reset()                    { *m = TokenInfoArgs{} }
func (m *TokenInfoArgs) String() string            { return proto1.CompactTextString(m) }
func (*TokenInfoArgs) ProtoMessage()               {}
func (*TokenInfoArgs) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *TokenInfoArgs) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *TokenInfoArgs) GetAppFrom() string {
	if m != nil {
		return m.AppFrom
	}
	return ""
}

func (m *TokenInfoArgs) GetAppChannel() string {
	if m != nil {
		return m.AppChannel
	}
	return ""
}

func (m *TokenInfoArgs) GetAppVer() int32 {
	if m != nil {
		return m.AppVer
	}
	return 0
}

func (m *TokenInfoArgs) GetUniqueId() string {
	if m != nil {
		return m.UniqueId
	}
	return ""
}

func (m *TokenInfoArgs) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type TokenInfoRes struct {
	Expire int64 `protobuf:"varint,1,opt,name=Expire" json:"Expire,omitempty"`
}

func (m *TokenInfoRes) Reset()                    { *m = TokenInfoRes{} }
func (m *TokenInfoRes) String() string            { return proto1.CompactTextString(m) }
func (*TokenInfoRes) ProtoMessage()               {}
func (*TokenInfoRes) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *TokenInfoRes) GetExpire() int64 {
	if m != nil {
		return m.Expire
	}
	return 0
}

type RefreshTokenArgs struct {
	UserId       int32  `protobuf:"varint,1,opt,name=UserId" json:"UserId,omitempty"`
	AppFrom      string `protobuf:"bytes,2,opt,name=AppFrom" json:"AppFrom,omitempty"`
	AppChannel   string `protobuf:"bytes,3,opt,name=AppChannel" json:"AppChannel,omitempty"`
	AppVer       int32  `protobuf:"varint,4,opt,name=AppVer" json:"AppVer,omitempty"`
	UniqueId     string `protobuf:"bytes,5,opt,name=UniqueId" json:"UniqueId,omitempty"`
	Token        string `protobuf:"bytes,6,opt,name=Token" json:"Token,omitempty"`
	RefreshToken string `protobuf:"bytes,7,opt,name=RefreshToken" json:"RefreshToken,omitempty"`
}

func (m *RefreshTokenArgs) Reset()                    { *m = RefreshTokenArgs{} }
func (m *RefreshTokenArgs) String() string            { return proto1.CompactTextString(m) }
func (*RefreshTokenArgs) ProtoMessage()               {}
func (*RefreshTokenArgs) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *RefreshTokenArgs) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *RefreshTokenArgs) GetAppFrom() string {
	if m != nil {
		return m.AppFrom
	}
	return ""
}

func (m *RefreshTokenArgs) GetAppChannel() string {
	if m != nil {
		return m.AppChannel
	}
	return ""
}

func (m *RefreshTokenArgs) GetAppVer() int32 {
	if m != nil {
		return m.AppVer
	}
	return 0
}

func (m *RefreshTokenArgs) GetUniqueId() string {
	if m != nil {
		return m.UniqueId
	}
	return ""
}

func (m *RefreshTokenArgs) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *RefreshTokenArgs) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

type RefreshTokenRes struct {
	Ret          int32  `protobuf:"varint,1,opt,name=Ret" json:"Ret,omitempty"`
	Msg          string `protobuf:"bytes,2,opt,name=Msg" json:"Msg,omitempty"`
	UserId       int32  `protobuf:"varint,3,opt,name=UserId" json:"UserId,omitempty"`
	Token        string `protobuf:"bytes,4,opt,name=Token" json:"Token,omitempty"`
	RefreshToken string `protobuf:"bytes,5,opt,name=RefreshToken" json:"RefreshToken,omitempty"`
	Expire       int64  `protobuf:"varint,6,opt,name=Expire" json:"Expire,omitempty"`
}

func (m *RefreshTokenRes) Reset()                    { *m = RefreshTokenRes{} }
func (m *RefreshTokenRes) String() string            { return proto1.CompactTextString(m) }
func (*RefreshTokenRes) ProtoMessage()               {}
func (*RefreshTokenRes) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *RefreshTokenRes) GetRet() int32 {
	if m != nil {
		return m.Ret
	}
	return 0
}

func (m *RefreshTokenRes) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *RefreshTokenRes) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *RefreshTokenRes) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *RefreshTokenRes) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *RefreshTokenRes) GetExpire() int64 {
	if m != nil {
		return m.Expire
	}
	return 0
}

type DestroyTokenArgs struct {
	UserId     int32  `protobuf:"varint,1,opt,name=UserId" json:"UserId,omitempty"`
	AppFrom    string `protobuf:"bytes,2,opt,name=AppFrom" json:"AppFrom,omitempty"`
	AppChannel string `protobuf:"bytes,3,opt,name=AppChannel" json:"AppChannel,omitempty"`
	AppVer     int32  `protobuf:"varint,4,opt,name=AppVer" json:"AppVer,omitempty"`
	UniqueId   string `protobuf:"bytes,5,opt,name=UniqueId" json:"UniqueId,omitempty"`
	Token      string `protobuf:"bytes,6,opt,name=Token" json:"Token,omitempty"`
}

func (m *DestroyTokenArgs) Reset()                    { *m = DestroyTokenArgs{} }
func (m *DestroyTokenArgs) String() string            { return proto1.CompactTextString(m) }
func (*DestroyTokenArgs) ProtoMessage()               {}
func (*DestroyTokenArgs) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *DestroyTokenArgs) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *DestroyTokenArgs) GetAppFrom() string {
	if m != nil {
		return m.AppFrom
	}
	return ""
}

func (m *DestroyTokenArgs) GetAppChannel() string {
	if m != nil {
		return m.AppChannel
	}
	return ""
}

func (m *DestroyTokenArgs) GetAppVer() int32 {
	if m != nil {
		return m.AppVer
	}
	return 0
}

func (m *DestroyTokenArgs) GetUniqueId() string {
	if m != nil {
		return m.UniqueId
	}
	return ""
}

func (m *DestroyTokenArgs) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type DestroyTokenRes struct {
	Ret int32 `protobuf:"varint,1,opt,name=Ret" json:"Ret,omitempty"`
}

func (m *DestroyTokenRes) Reset()                    { *m = DestroyTokenRes{} }
func (m *DestroyTokenRes) String() string            { return proto1.CompactTextString(m) }
func (*DestroyTokenRes) ProtoMessage()               {}
func (*DestroyTokenRes) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *DestroyTokenRes) GetRet() int32 {
	if m != nil {
		return m.Ret
	}
	return 0
}

func init() {
	proto1.RegisterType((*TokenInfoArgs)(nil), "proto.TokenInfoArgs")
	proto1.RegisterType((*TokenInfoRes)(nil), "proto.TokenInfoRes")
	proto1.RegisterType((*RefreshTokenArgs)(nil), "proto.RefreshTokenArgs")
	proto1.RegisterType((*RefreshTokenRes)(nil), "proto.RefreshTokenRes")
	proto1.RegisterType((*DestroyTokenArgs)(nil), "proto.DestroyTokenArgs")
	proto1.RegisterType((*DestroyTokenRes)(nil), "proto.DestroyTokenRes")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for AuthService service

type AuthServiceClient interface {
	Auth(ctx context.Context, in *UserLoginReq, opts ...grpc.CallOption) (*BaseAck, error)
	TokenInfo(ctx context.Context, in *TokenInfoArgs, opts ...grpc.CallOption) (*TokenInfoRes, error)
	RefreshToken(ctx context.Context, in *RefreshTokenArgs, opts ...grpc.CallOption) (*RefreshTokenRes, error)
	DestroyToken(ctx context.Context, in *DestroyTokenArgs, opts ...grpc.CallOption) (*DestroyTokenRes, error)
}

type authServiceClient struct {
	cc *grpc.ClientConn
}

func NewAuthServiceClient(cc *grpc.ClientConn) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) Auth(ctx context.Context, in *UserLoginReq, opts ...grpc.CallOption) (*BaseAck, error) {
	out := new(BaseAck)
	err := grpc.Invoke(ctx, "/proto.AuthService/Auth", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) TokenInfo(ctx context.Context, in *TokenInfoArgs, opts ...grpc.CallOption) (*TokenInfoRes, error) {
	out := new(TokenInfoRes)
	err := grpc.Invoke(ctx, "/proto.AuthService/TokenInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) RefreshToken(ctx context.Context, in *RefreshTokenArgs, opts ...grpc.CallOption) (*RefreshTokenRes, error) {
	out := new(RefreshTokenRes)
	err := grpc.Invoke(ctx, "/proto.AuthService/RefreshToken", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) DestroyToken(ctx context.Context, in *DestroyTokenArgs, opts ...grpc.CallOption) (*DestroyTokenRes, error) {
	out := new(DestroyTokenRes)
	err := grpc.Invoke(ctx, "/proto.AuthService/DestroyToken", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AuthService service

type AuthServiceServer interface {
	Auth(context.Context, *UserLoginReq) (*BaseAck, error)
	TokenInfo(context.Context, *TokenInfoArgs) (*TokenInfoRes, error)
	RefreshToken(context.Context, *RefreshTokenArgs) (*RefreshTokenRes, error)
	DestroyToken(context.Context, *DestroyTokenArgs) (*DestroyTokenRes, error)
}

func RegisterAuthServiceServer(s *grpc.Server, srv AuthServiceServer) {
	s.RegisterService(&_AuthService_serviceDesc, srv)
}

func _AuthService_Auth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserLoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Auth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AuthService/Auth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Auth(ctx, req.(*UserLoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_TokenInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenInfoArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).TokenInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AuthService/TokenInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).TokenInfo(ctx, req.(*TokenInfoArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_RefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshTokenArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).RefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AuthService/RefreshToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).RefreshToken(ctx, req.(*RefreshTokenArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_DestroyToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroyTokenArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).DestroyToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AuthService/DestroyToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).DestroyToken(ctx, req.(*DestroyTokenArgs))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Auth",
			Handler:    _AuthService_Auth_Handler,
		},
		{
			MethodName: "TokenInfo",
			Handler:    _AuthService_TokenInfo_Handler,
		},
		{
			MethodName: "RefreshToken",
			Handler:    _AuthService_RefreshToken_Handler,
		},
		{
			MethodName: "DestroyToken",
			Handler:    _AuthService_DestroyToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}

func init() { proto1.RegisterFile("auth.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 388 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x53, 0xcd, 0x4e, 0xe3, 0x30,
	0x18, 0xac, 0x37, 0x4d, 0xba, 0xfd, 0xda, 0xdd, 0x56, 0x6e, 0xd5, 0xb5, 0x72, 0x58, 0x55, 0x5e,
	0x69, 0xd5, 0xcb, 0xf6, 0xb0, 0x5c, 0xb8, 0x86, 0x3f, 0xa9, 0x12, 0x5c, 0x0c, 0xe5, 0x1e, 0xda,
	0xaf, 0x49, 0x54, 0x48, 0x5c, 0x27, 0x45, 0xf0, 0x34, 0x3c, 0x00, 0x12, 0x0f, 0xc3, 0xf3, 0x70,
	0x40, 0x71, 0x42, 0x94, 0x84, 0x8a, 0x33, 0x9c, 0xe2, 0x99, 0x71, 0x3e, 0xcd, 0x8c, 0x6d, 0x00,
	0x77, 0x9b, 0xf8, 0x53, 0xa9, 0xa2, 0x24, 0xa2, 0xa6, 0xfe, 0xd8, 0x1d, 0xd7, 0xc3, 0x30, 0xc9,
	0x38, 0xfe, 0x48, 0xe0, 0xc7, 0x45, 0xb4, 0xc6, 0x70, 0x16, 0xae, 0x22, 0x47, 0x79, 0x31, 0x1d,
	0x81, 0x35, 0x8f, 0x51, 0xcd, 0x96, 0x8c, 0x8c, 0xc9, 0xc4, 0x14, 0x39, 0xa2, 0x0c, 0x5a, 0x8e,
	0x94, 0x27, 0x2a, 0xba, 0x61, 0xdf, 0xc6, 0x64, 0xd2, 0x16, 0x6f, 0x90, 0xfe, 0x06, 0x70, 0xa4,
	0x3c, 0xf4, 0xdd, 0x30, 0xc4, 0x6b, 0x66, 0x68, 0xb1, 0xc4, 0xa4, 0x13, 0x1d, 0x29, 0x2f, 0x51,
	0xb1, 0x66, 0x36, 0x31, 0x43, 0xd4, 0x86, 0xef, 0xf3, 0x30, 0xd8, 0x6c, 0x71, 0xb6, 0x64, 0xa6,
	0xfe, 0xab, 0xc0, 0x74, 0x08, 0xa6, 0xb6, 0xc5, 0x2c, 0x2d, 0x64, 0x80, 0xff, 0x85, 0x6e, 0x61,
	0x56, 0xa0, 0xf6, 0x7a, 0x7c, 0x27, 0x03, 0x85, 0xda, 0xab, 0x21, 0x72, 0xc4, 0x9f, 0x09, 0xf4,
	0x05, 0xae, 0x14, 0xc6, 0xbe, 0xde, 0xff, 0xd9, 0x83, 0x51, 0x0e, 0xdd, 0xb2, 0x5f, 0xd6, 0xd2,
	0x62, 0x85, 0xe3, 0x0f, 0x04, 0x7a, 0x65, 0x22, 0x2d, 0xa0, 0x0f, 0x86, 0xc0, 0x24, 0x0f, 0x94,
	0x2e, 0x53, 0xe6, 0x2c, 0xf6, 0xf2, 0x24, 0xe9, 0xb2, 0x94, 0xdb, 0xa8, 0xe4, 0x2e, 0x9c, 0x34,
	0x3f, 0x72, 0x62, 0xbe, 0x77, 0x52, 0xaa, 0xdd, 0xaa, 0xd4, 0xfe, 0x44, 0xa0, 0x7f, 0x84, 0x71,
	0xa2, 0xa2, 0xfb, 0x2f, 0x51, 0x3b, 0xff, 0x03, 0xbd, 0xb2, 0xdf, 0x9d, 0x8d, 0xfe, 0x7f, 0x21,
	0xd0, 0x71, 0xb6, 0x89, 0x7f, 0x8e, 0xea, 0x36, 0x58, 0x20, 0xfd, 0x07, 0xcd, 0x14, 0xd2, 0x41,
	0xf6, 0x84, 0xa6, 0x69, 0x9e, 0xd3, 0xc8, 0x0b, 0x42, 0x81, 0x1b, 0xfb, 0x67, 0x4e, 0x1e, 0xb8,
	0x31, 0x3a, 0x8b, 0x35, 0x6f, 0xd0, 0x7d, 0x68, 0x17, 0x77, 0x96, 0x0e, 0x73, 0xb9, 0xf2, 0xe4,
	0xec, 0x41, 0x9d, 0x15, 0x18, 0xf3, 0x06, 0x75, 0xaa, 0x47, 0x41, 0x7f, 0xe5, 0xdb, 0xea, 0x37,
	0xdb, 0x1e, 0xed, 0x10, 0x8a, 0x11, 0xe5, 0x80, 0xc5, 0x88, 0xfa, 0x29, 0x15, 0x23, 0x6a, 0x75,
	0xf0, 0xc6, 0x95, 0xa5, 0x85, 0xbd, 0xd7, 0x00, 0x00, 0x00, 0xff, 0xff, 0x2d, 0xf4, 0x37, 0xf5,
	0x4a, 0x04, 0x00, 0x00,
}
