// Code generated by gen_proto.sh.
// DO NOT EDIT!
package client_handler

import . "chess/agent/types"

var Code = map[string]int16{
	"heart_beat_req":         0,    // 心跳包..
	"heart_beat_ack":         1,    // 心跳包回复
	"user_login_req":         10,   // 登陆
	"user_login_ack": 		  11,   // 登陆成功
	"get_seed_req":           30,   // socket通信加密使用
	"get_seed_ack":           31,   // socket通信加密使用

	"centre_ping_req":        1001, //  ping
	"centre_ping_ack":        1002, //  pong

	"room_ping_req":          2001, //  ping
	"room_ping_ack":          2002, //  ping回复
}

var RCode = map[int16]string{
	0:    "heart_beat_req",         // 心跳包..
	1:    "heart_beat_ack",         // 心跳包回复
	10:   "user_login_req",         // 登陆
	11:   "user_login_ack", 	// 登陆成功
	30:   "get_seed_req",           // socket通信加密使用
	31:   "get_seed_ack",           // socket通信加密使用
	1001: "centre_ping_req",        //  ping
	1002: "centre_ping_ack",        //  pong
	2001: "room_ping_req",          //  ping
	2002: "room_ping_ack",          //  ping回复
}

var Handlers map[int16]func(*Session, []byte) []byte

func init() {
	Handlers = map[int16]func(*Session, []byte) []byte{
		2001:  P_room_ping_req,
	}
}
